"""fnirsi_ps_control – PC control for the FNIRSI DPS-150 power supply."""
# Version resolution order:
#   1. importlib.metadata  – works for any installed (editable or wheel) package
#   2. _version.py         – generated by hatch-vcs at build time; present in
#                            sdist / wheel but not in a raw git checkout
#   3. hard-coded fallback – last resort for bare git clones without a build step

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _meta_version

try:
    __version__: str = _meta_version("fnirsi-ps-control")
except PackageNotFoundError:
    try:
        from fnirsi_ps_control._version import __version__  # type: ignore[no-redef,import]
    except ImportError:
        __version__ = "0.0.0.dev0"

__all__ = ["__version__"]
