#!/usr/bin/env python3
"""Generate docs/protocol/reference.md from protocol/fnirsi_dps150.ksy.

Usage:
    uv run python scripts/ksy_to_md.py \\
        --ksy protocol/fnirsi_dps150.ksy \\
        --out docs/protocol/reference.md
"""

from __future__ import annotations

import argparse
import textwrap
from pathlib import Path
from typing import Any

import yaml  # type: ignore[import-untyped]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Direction byte values as defined in the `direction` enum
_DIR_TX = 0xF1  # host → device
_DIR_RX = 0xF0  # device → host


def _ks_type_label(t: Any) -> str:  # noqa: ANN401
    """Human-readable label for a KS field type."""
    if isinstance(t, str):
        mapping = {
            "u1": "u8",
            "u2": "u16 LE",
            "u4": "u32 LE",
            "f4": "f32 LE",
            "f8": "f64 LE",
            "s1": "i8",
            "s2": "i16 LE",
            "s4": "i32 LE",
            "str": "ASCII string",
        }
        return mapping.get(t, t)
    if isinstance(t, dict):
        if "switch-on" in t:
            return "payload (switch)"
    return str(t)


def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    cols = len(headers)
    widths = [max(len(h), max((len(r[i]) for r in rows), default=0)) for i, h in enumerate(headers)]
    sep = "| " + " | ".join("-" * w for w, _ in zip(widths, headers, strict=True)) + " |"
    head = "| " + " | ".join(h.ljust(w) for h, w in zip(headers, widths, strict=True)) + " |"
    body = "\n".join(
        "| " + " | ".join(str(r[i]).ljust(widths[i]) for i in range(cols)) + " |" for r in rows
    )
    return f"{head}\n{sep}\n{body}"


# ---------------------------------------------------------------------------
# Section renderers
# ---------------------------------------------------------------------------


def render_header(ksy: dict[str, Any]) -> str:
    meta = ksy.get("meta", {})
    rows = [
        ["ID", str(meta.get("id", ""))],
        ["Title", str(meta.get("title", ""))],
        ["KS version", str(meta.get("ks-version", ""))],
        ["Endian", str(meta.get("endian", ""))],
        ["License", str(meta.get("license", ""))],
    ]
    table = _md_table(["Property", "Value"], rows)
    # Extract wire-format lines from the file-level comment (ksy has no meta.doc here)
    sections = [
        "<!-- AUTO-GENERATED by scripts/ksy_to_md.py — do not edit manually -->",
        "",
        "# Protocol Reference",
        "",
        "Single source of truth: `protocol/fnirsi_dps150.ksy`",
        "",
        "## Overview",
        "",
        table,
        "",
    ]
    return "\n".join(sections)


def render_enums(ksy: dict[str, Any]) -> str:
    enums: dict[str, dict[int, str]] = ksy.get("enums", {})
    if not enums:
        return ""
    out = ["## Enumerations", ""]
    for name, values in enums.items():
        out.append(f"### `{name}`")
        out.append("")
        rows = [[f"`0x{v:02X}`", k] for v, k in sorted(values.items())]
        out.append(_md_table(["Value (hex)", "Name"], rows))
        out.append("")
    return "\n".join(out)


def _payload_cases(ksy: dict[str, Any]) -> tuple[dict[int, str], dict[int, str]]:
    """Return (tx_map, rx_map): cmd_byte → payload_type_name for each direction."""
    types: dict[str, Any] = ksy.get("types", {})
    cmd_body_seq: list[dict[str, Any]] = types.get("command_body", {}).get("seq", [])
    raw_cases: dict[int, str] = {}
    for field in cmd_body_seq:
        if field.get("id") == "payload":
            t = field.get("type", {})
            if isinstance(t, dict):
                raw_cases = t.get("cases", {})
            break

    tx_map: dict[int, str] = {}
    rx_map: dict[int, str] = {}
    for key, payload_type in raw_cases.items():
        dir_byte = (key >> 8) & 0xFF
        cmd_byte = key & 0xFF
        if dir_byte == _DIR_TX:
            tx_map[cmd_byte] = payload_type
        elif dir_byte == _DIR_RX:
            rx_map[cmd_byte] = payload_type
    return tx_map, rx_map


def render_commands(ksy: dict[str, Any]) -> str:
    enums: dict[str, Any] = ksy.get("enums", {})
    cmd_enum: dict[int, str] = enums.get("command_id", {})
    types: dict[str, Any] = ksy.get("types", {})
    tx_map, rx_map = _payload_cases(ksy)

    rows = []
    for cmd_val, cmd_name in sorted(cmd_enum.items()):
        tx_type = tx_map.get(cmd_val)
        rx_type = rx_map.get(cmd_val)

        if tx_type and rx_type:
            direction = "TX + RX"
        elif tx_type:
            direction = "TX"
        else:
            direction = "RX"

        # Brief description: prefer RX payload doc (responses are more descriptive than queries)
        payload_type = rx_type or tx_type or ""
        payload_doc = ""
        if payload_type:
            raw_doc = types.get(payload_type, {}).get("doc", "")
            first_line = str(raw_doc).splitlines()[0] if raw_doc else ""
            payload_doc = textwrap.shorten(first_line, width=55)

        rows.append([
            f"`0x{cmd_val:02X}`",
            f"`{cmd_name}`",
            direction,
            f"`{tx_type}`" if tx_type else "—",
            f"`{rx_type}`" if rx_type else "—",
            payload_doc,
        ])

    out = ["## Command Catalogue", ""]
    out.append(_md_table(["CMD", "Name", "Direction", "TX Payload", "RX Payload", "Description"], rows))
    out.append("")

    # Session-start magic note
    out += [
        "!!! note \"Session-start magic (START=`0xb0`)\"",
        "    Sent once after the CONNECT/READY handshake. Uses a non-standard 4-byte",
        "    body without CMD/LEN/CHKSUM — see `session_magic_body`.",
        "",
    ]

    return "\n".join(out)


def render_types(ksy: dict[str, Any]) -> str:
    types: dict[str, Any] = ksy.get("types", {})
    # Structural container types rendered separately in the Command Catalogue section
    skip = {"frame", "command_body"}
    out = ["## Payload Types", ""]
    for type_name, typedef in types.items():
        if type_name in skip:
            continue
        doc = textwrap.dedent(str(typedef.get("doc", ""))).strip()
        seq: list[dict[str, Any]] = typedef.get("seq", [])
        out.append(f"### `{type_name}`")
        out.append("")
        if doc:
            # First line as brief, remaining as blockquote if present
            lines = doc.splitlines()
            out.append(lines[0])
            out.append("")
        if seq:
            rows = []
            for field in seq:
                fname = str(field.get("id", ""))
                ftype = _ks_type_label(field.get("type", ""))
                fdoc = str(field.get("doc", "")).replace("\n", " ").strip()
                repeat = field.get("repeat")
                repeat_expr = field.get("repeat-expr")
                if repeat == "expr" and repeat_expr:
                    ftype += f" ×{repeat_expr}"
                if field.get("size-eos"):
                    ftype = "bytes (rest)"
                if "contents" in field:
                    contents = field["contents"]
                    hex_str = " ".join(f"0x{b:02x}" for b in contents)
                    ftype = f"fixed bytes `[{hex_str}]`"
                fenum = field.get("enum")
                if fenum:
                    ftype += f" (enum: `{fenum}`)"
                rows.append([f"`{fname}`", ftype, fdoc])
            out.append(_md_table(["Field", "Type", "Description"], rows))
            out.append("")
        else:
            out.append("_(no fields)_")
            out.append("")
    return "\n".join(out)


def render_checksum() -> str:
    return "\n".join(
        [
            "## Checksum",
            "",
            "Every frame ends with a 1-byte checksum:",
            "",
            "```",
            "CHKSUM = (CMD + LEN + Σ DATA bytes) mod 256",
            "```",
            "",
            "The `DIR` and `START` bytes are **excluded** from the checksum calculation.",
            "Confirmed by byte-exact comparison against captured frames.",
            "",
        ]
    )


def render_diagram() -> str:
    return "\n".join(
        [
            "## Structure Diagram",
            "",
            "![Protocol structure diagram](fnirsi_dps150.svg)",
            "",
        ]
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--ksy", required=True, type=Path, help="Path to .ksy file")
    p.add_argument("--out", required=True, type=Path, help="Output Markdown file")
    return p.parse_args()


def load_ksy(path: Path) -> dict[str, Any]:
    with path.open() as f:
        return yaml.safe_load(f)  # type: ignore[no-any-return]


def main() -> None:
    args = parse_args()
    ksy = load_ksy(args.ksy)

    sections = [
        render_header(ksy),
        render_enums(ksy),
        render_commands(ksy),
        render_types(ksy),
        render_checksum(),
        render_diagram(),
    ]
    content = "\n".join(sections)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content)
    print(f"Written: {args.out}")


if __name__ == "__main__":
    main()
